# Generated by Django 5.2.1 on 2025-05-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='country',
            new_name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_lan_en',
            field=models.CharField(max_length=32, null=True, verbose_name='Язык курса:'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_lan_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Язык курса:'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='variant_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='variant_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='questions_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='questions_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
